FROM postgres:16beta1-alpine

ENV POSTGRES_USER=$DB_USER

ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD

ENV POSTGRES_DB=$DB_NAME

COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432

CMD ["postgres"]
