version: '3.9'
services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 80:80
    networks:
      - frontend
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - frontend
      - backend
    environment:
      - SESSION_KEY=$SESSION_KEY
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER

  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    expose:
      - 5432
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER

volumes:
  pgdata:
networks:
  frontend:
  backend:
