version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - loginnet
    environment:
      - SESSION_KEY=$SESSION_KEY
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER

  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    expose:
      - 5432
    networks:
      - loginnet
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER

networks:
  loginnet:
