FROM nginx:latest

RUN apt update && \
    apt install iputils-ping -y && apt install vim -y && \
    apt install curl -y

WORKDIR /frontend

COPY frontend/ /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
