name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SESSION_KEY: ${{ secrets.SESSION_KEY }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and run containers
        run: |
          docker-compose up -d --build

      - name: Run unit tests with pytest
        run: |
          container_id=$(docker ps --filter "name=postgres-login-service_app_1" --format "{{.ID}}")
          docker exec $container_id pytest

      - name: Lint with flake8
        run: flake8 --filename=server.py app/
