name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10-alpine
    env:
      SESSION_KEY: ${{ secrets.SESSION_KEY }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run:  docker-compose up -d

      - name: Wait for PostgreSQL
        run: |
          until nc -zv localhost 5432; do sleep 5; done

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements.txt

      - name: Run unit tests with pytest
        run: |
          export SESSION_KEY=$SESSION_KEY
          pytest

      - name: Lint with flake8
        run: flake8 --filename=server.py app/
