name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SESSION_KEY: ${{ secrets.SESSION_KEY }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    services:
      db:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and run containers
        run: |
          docker-compose up -d --build

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements.txt

      - name: Run unit tests with pytest
        run: |
          export SESSION_KEY=$SESSION_KEY
          export POSTGRES_PASSWORD=$POSTGRES_PASSWORD

      - name: Lint with flake8
        run: flake8 --filename=server.py app/
